name: exercise2
on:
  workflow_dispatch
jobs:
  step1:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo "Hello, Step1."
  step2:
    needs: step1
    runs-on: ubuntu-latest
    steps:
      - name: step2
        run: echo "Hello, Step2."
  step3:
    runs-on: ubuntu-latest
    steps:
      - name: step3
        run: echo "Hello, Step3."
